### ISSUE TITLE
Progress logging when fully synced

### ISSUE THREAD

**Issue by cpacia** [gcash/bchd#115]
The logging looks like this:
```
SYNC: Processed 1 block in the last 17m36.6s (304 transactions, height 555567 of 555554, progress 100.00%, 2018-11-06 23:29:18 -0500 EST, ~2 MiB cache)
```

Maybe it should stop logging progress when fully synced. @swdee what do you think about this?

**Comment by zquestz** [comment]
I think we can save space as well. How about:

```
SYNC: Processed 1 block in 17m36.6s (304 txs, height 555567 of 555554, progress 100.00%, 2018-11-06 23:29:18 -0500 EST, ~2 MiB cache)
```

Then also remove progress when it is complete. Although I don't mind it being there.

**Comment by zquestz** [comment]
One last thing, it seems the denominator isn't calculated correctly. How are you at a height past the 'of' clause. Something isn't quite right. @swdee

**Comment by cpacia** [comment]
I think the denominator is the height of the sync peer when the sync started. And the numerator is the current height. Yeah it's messed up. Should probably remove this part of the log after the sync is complete.

**Comment by zquestz** [comment]
We should use similar logic to the topBlock approach I took for the sync peer code. That will always display the correct top height.

**Comment by swdee** [comment]
Part of the reason for adding this type of metric in is to get an insight as to what bchd is doing as its quite opaque.  

The current logic is using the best peer's last block height to determine the SyncHeight which replicates the method used in Decred.  This does cause the SyncHeight to change when bchd decides on a new best peer.  I also looked at the Bitcoin C++ implementation which does it differently by estimating the SyncHeight from the current blocks timestamp and now().  Neither of them are precise and I agree it looks a funny when you have `height 555567 of 555554`.

I'll take a look at the topBlock idea tomorrow and see if it portrays a more accurate statistic.

**Comment by swdee** [comment]
@cpacia  Would you attach the bchd.log with the reported `height 555567 of 555554` please so I can take a look at some prior logging.  I am wondering if there was a syncPeer change that has occurred prior which was reporting a lower LastBlock() number of 555554.

I have added some further debugging to my test instance but currently it is reporting fine so will need to wait some time too see what is causing it to offset.

**Comment by swdee** [comment]
@cpacia don't worry about the bchd.log as I have now found the problem.

The issue is setting of variable syncHeight at https://github.com/gcash/bchd/blob/97ae6ea9d1e7e443f21bbd641c338eb3b6153553/netsync/manager.go#L382 becoming stale as its only set when new best peer is established.  So the fix is to retrieve LastBlock() from within the SyncHeight() function.

Further more there is actually a data race between the bestPeer.LastBlock() and a new block being processed which causes the block height to be one higher than LastBlock() as bchd can validate the new block quicker than the communications occurring with bestPeer so we get an offset of one on the height, eg: `height 1266723 of 1266722, progress 100.00%`

So I propose the following changes;

1. Fix the stale variable usage
2. Shorten the progress output to @zquestz format of `height 1260193/1266701 (99.49%)`
3. Adjust the code to handle the data race so an up to date chain reports `height 1266701 (100.00%)`

**Comment by zquestz** [comment]
That sounds fantastic @swdee =)

**Comment by zquestz** [comment]
This is all done. Thanks @swdee =)
