### ISSUE TITLE
gRPC API GetTransaction returns "invalid transaction hash" despite being given valid transaction

### ISSUE THREAD

**Issue by postables** [gcash/bchd#231]
I'm testing out retrieving transactions via the gRPC `GetTransaction` call, and any hash I've found off the [explorer.bitcoin.com](https://explorer.bitcoin.com) will return the following error code
```
rpc error: code = InvalidArgument desc = invalid transaction hash
```

Any of the transactions that fail, will not give any errors when ran through `bchctl getrawtransaction <hash>`.  It seems like these lines of code form [bchrpc/server.go](https://github.com/gcash/bchd/blob/8717f0400dcba02b041cacd4211e2a349d4c1bbf/bchrpc/server.go#L588-L591) is what's causing the error.

An example [transaction](https://explorer.bitcoin.com/bch/tx/63cf1d240f76e0e6f0a4fd57657bcbef334d8ce688206bd736d3356617824fa5) that will cause an error with the gRPC call but not `bchctl`.

output from `bchctl getinfo`

```
{
  "version": 140300,
  "protocolversion": 70015,
  "blocks": 583050,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 314290737551.8507,
  "testnet": false,
  "relayfee": 0.00001,
  "errors": ""
}
```

bchd version: `bchd version 0.14.3`

**Comment by cpacia** [comment]
So this is maybe a little bit of a quirk but most bitcoin codebases treat byte arrays as little endian and hex strings as big endian. Since this accepts a byte array it's expecting little endian. 

If you're using go you can use the `chainhash` object and do `h := chainhash.NewFromString("txid hex here")` and then use it as `h[:]`. If you're using another language you'll just need to reverse the bytes.

**Comment by postables** [comment]
That worked, thank you :D
