### ISSUE TITLE
confirmations: -2146855420

### ISSUE THREAD

**Issue by readcash** [gcash/bchd#351]
We're seeing weird responses from fountainhead.cash's BCHD node:

```
height: 2147483647
confirmations: -2146855420
```

This might indicate a bug in BCHD, but we're not sure yet. 2147483647 is 2^32, so it seems like it was incrementing too fast. Which might indicate a bug in BCHD. Currently, it seems like they forked from Bitcoin Cash network

https://read.cash/forum/readcash/wallet-balance-709ec680#post-6bd09e0b

Thought you might be interested in this

**Comment by readcash** [comment]
The response was in `GetAddressUnspentOutputs`

**Comment by blockparty-sh** [comment]
Hi! This was due to shutdown of server that led to bchd getting killed prior to it being able to complete its shutdown. I've increased `TimeoutSec` in systemd service file to reasonable level - prior this was not set. 

On restart of BCHD it did not perform the reprocessing automatically. This would probably be a good improvement.

**Comment by cpacia** [comment]
> This would probably be a good improvement.

There is code to do it but there is a bug in it that causes it to sometimes fail that is very difficult to figure out.

**Comment by readcash** [comment]
https://read.cash/@quest/quick-wallet-zero-balance-fix-244f0868#comment-9fabc8c4
