### ISSUE TITLE
Add fee/standardness checks to gRPC submitTransaction

### ISSUE THREAD

**Issue by zquestz** [gcash/bchd#382]
Currently if someone submits a non-standard transaction the node will accept it then not forward it to any other peers. This can happen due to the fee being too low, or other rules.

We should add an `allow-non-standard` boolean flag to the SubmitTransactionRequest so we can throw an intelligent error if the transaction won't propagate.

We should also add a high fee check, much like the JSON RPC to protect users from setting too high a fee as well.

**Comment by readcash** [comment]
Yep, that would help us greatly. We've got into a situation where by accidentally sending a low-fee transaction that won't propagate, got ourselves in a consistent bubble which required multiple restarts to figure out, since UTXOs were updated too. So we were spending money that nobody else in the BCH network agreed we have.

High fee check is something I've got into multiple times while developing stuff by sending a transaction, which included only a very small output (thereby accidentally donating everything else to a miner)

👍

**Comment by zquestz** [comment]
Now that we have landed PR#383 we probably don't need the standardness flag. We won't accept low/zero fee transactions by default. That still leaves us the high fee flag which will be useful!

**Comment by readcash** [comment]
@cpacia Even though the issue is closed, we're still seeing people get into the consistent bubbles (I don't know yet how), i.e. for them it seems like they are doing something (sending money, tipping), balance changes as expected, but the rest of the network doesn't see it. As soon as I ask to restart the BCHD node, all these transactions are gone. So that makes me not 100% certain that this was completely solved. I don't have any data yet to find out what happens though, so it's merely to inform you about what's happening. We have to ask to restart the node every few days after complaints.
