### ISSUE TITLE
Implement BIP-152 (CompactBlocks)

### ISSUE THREAD

**Issue by zquestz** [gcash/bchd#66]
Currently bchd does not support CompactBlocks or XThin. We really should look into adding one of these block propagation improvements. This will make connecting to peers far more reliable as we can bump the version on the connection.

https://github.com/bitcoin/bips/blob/master/bip-0152.mediawiki

There is also an open issue on btcd: https://github.com/btcsuite/btcd/issues/1208

**Comment by cpacia** [comment]
That was my initial thought though graphene doesn't currently have a spec. Not clear what the timeline is on it either.

**Comment by zquestz** [comment]
I am all for Graphene but think we should wait for the spec that doesn't include ordering information. =)

For now I want to try and get our protocol version to 70015 and support at least Compact Blocks for now. If someone wants to do XThin I wouldn't be against it either. =)

**Comment by swdee** [comment]
I am doubtful we will see a BIP for Graphene, but a draft BUIP exists at https://github.com/BitcoinUnlimited/BUIP/blob/master/093.mediawiki 

However that aside since this ticket is about Compact Blocks, gocoin has it implemented if your wanting to review some other references/implementations. 
 https://github.com/piotrnar/gocoin/blob/550d5242ea3fc61a86e9ba948f641a6ad14e2b1d/client/network/cblk.go

**Comment by swdee** [comment]
@zquestz How is progress with compact blocks?   

I just found this implementation on another btcd fork https://github.com/copernet/copernicus/commit/4e9dd29ff0a516c1807107f4534296491ab76c5b#diff-5f9e0ae7ac1627daa2427f1a2d23047a

Seems they have commented the code out in later commits but but looks like a lot of the work has been done.

**Comment by zquestz** [comment]
@swdee thanks! Progress hasn't been as fast as I expected. Been busy the past week or so. I checked out the other implementation and it looks pretty complete. Thanks for the heads up. =)
